- name: Create user
  hosts: main
  become: true

  tasks:

    - name: Ensure that variables are set
      assert:
        that:
          - user is defined
          - pubkey is defined
        fail_msg: "Error: Missing required variables: user"

    - name: Create a user 
      ansible.builtin.user:
        name: "{{ user }}"
        create_home: yes
        groups: wheel
        
    - name: Create ssh folder
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        mode: 0755
        state: directory 

    - name: Set authorized key
      ansible.builtin.copy:
        owner: "{{ user }}"
        group: "{{ user }}"
        dest: "/home/{{ user }}/.ssh/authorized_keys"
        content: "{{ pubkey }}"
        mode: 0600