# ansible-playbook -i hosts.yml -u root centos/create-user.yml -e user=$USER -e keypath=$PUBKEYPATH disableroot=true

- name: Create user
  hosts: main
  become: true

  tasks:

    - name: Ensure that variables are set
      assert:
        that:
          - user is defined
          - keypath is defined
        fail_msg: "Error: Missing required variables: user, keypath"

    - name: Create a user 
      ansible.builtin.user:
        name: "{{ user }}"
        create_home: yes
        groups: wheel
        
    - name: Create ssh folder
      ansible.builtin.file:
        owner: "{{ user }}"
        group: "{{ user }}"
        path: "/home/{{ user }}/.ssh"
        mode: 0755
        state: directory 

    - name: Set authorized key
      ansible.builtin.copy:
        owner: "{{ user }}"
        group: "{{ user }}"
        dest: "/home/{{ user }}/.ssh/authorized_keys"
        content: "{{ lookup('file', keypath) }}"
        mode: 0600

    - name: Clear root login
      when: disableroot is defined
      ansible.builtin.file:
        path: /root/.ssh/authorized_keys
        state: absent 