- name: Install git and clone
  hosts: main
  become: true

  tasks:
    - name: Update packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install git
      ansible.builtin.dnf:
        name:
          - git
        state: latest
