# ansible-playbook -i hosts.yml -u $USER centos/install-git-and-clone.yml -K -e keypath=$DEPLOYKEY --private-key $SSHKEY

- name: Install git
  hosts: main

  tasks:
    - name: Update packages
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install git
      become: true
      ansible.builtin.dnf:
        name:
          - git
        state: latest

    - name: Copy ssh key
      ansible.builtin.copy:
        src: "{{ keypath }}"
        dest: ~/.ssh/deploykey
        mode: 0600
    - name: Set config
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        create: true
        block: |
          Host github.com
            User git
            IdentityFile ~/.ssh/deploykey
         
         
        