# ansible-playbook digitalocean-droplet-delete.yml -K -e token=$TOKEN -e name=$NAME

- name: Delete droplet
  hosts: localhost
  become: yes

  tasks: 
    - name: Ensure that variables are set
      assert:
        that:
          -  token is defined
          -  name is defined
        fail_msg: "Error: Missing required variables: token, name"

    - name: Fetch Droplet
      community.digitalocean.digital_ocean_droplet_info:
        api_token: "{{ token }}"
        name: "{{ name }}"
      register: droplet 

    - name: Display Droplet
      ansible.builtin.debug:
        msg: "{{ droplet }}"

    - name: Delete Droplet
      community.digitalocean.digital_ocean_droplet:
        api_token: "{{ token }}"
        state: absent
        name: "{{ name }}"
        id: "{{ droplet[0].id }}"
      register: my_droplet
