# ansible-playbook create-digitalocean-droplet.yml -K -e token=$TOKEN -e name=$NAME -e image=$IMAGE -e size=$SIZE

- name: Create new droplet
  hosts: localhost
  become: yes
  
  vars:
    public_key : "76:ae:9d:1b:49:fa:e3:9c:00:91:f9:9e:c9:0c:93:85"
  
  tasks: 
    - name: Ensure that variables are set
      assert:
        that:
          -  token is defined
          -  name is defined
        fail_msg: "Error: Missing required variables: token, name"
 
    - name: Create a new Droplet
      community.digitalocean.digital_ocean_droplet:
        api_token: "{{ token }}"
        state: active
        project: first-project
        name: "{{ name }}"
        region: nyc3
        image: "{{ image or 'centos-stream-9-x64' }}"
        size: "{{ size or 's-1vcpu-2gb' }}"
        wait_timeout: 500
        ssh_keys: [ "{{ public_key }}" ]
      register: my_droplet

    - name: Display IP address
      ansible.builtin.debug:
        msg: "{{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}" 